export const DOC_REQUIREMENTS = {
  member_organization: [
    { category:'corporate_certificate', label:'Certificate of Incorporation / Registration Document', required:true, desc:'Official document proving legal entity status.' },
    { category:'bylaws', label:'Bylaws / Governing Documents', required:true, desc:'Organizational constitution or governing framework.' },
    { category:'tax_id_document', label:'EIN or National Tax / Organization Identification Number', required:true, desc:'Tax identification document for KYB and tax reporting.' },
    { category:'officer_resolution', label:'Officer Resolution / Authorized Representative Declaration', required:true, desc:'Listing the full names and emails of all elected Board of Directors and current officers.' },
    { category:'address_confirmation', label:'Proof of Permanent Address', required:true, desc:'Utility bill, lease, or official document confirming address.' },
    { category:'community_wellbeing_declaration', label:'Community Well-Being Declaration', required:true, desc:'Statement that the entity exists to further community well-being.' },
    { category:'ethics_declaration', label:'Professional Ethics Declaration', required:true, desc:'Commitment to highest professional ethics standards.' },
    { category:'membership_summary', label:'Membership Summary', required:true, desc:'Summary of current membership or estimated member count.' },
    { category:'tax_exemption', label:'Tax Exemption / Nonprofit Registration', required:false, desc:'Tax-exempt status or 501(c)(3) document if applicable.' },
    { category:'annual_report', label:'Annual Report', required:false, desc:'Most recent annual report (preferred).' },
    { category:'partnership_proposal', label:'Partnership Proposal', required:false, desc:'Proposed partnership or activation plan (preferred).' },
  ],
  entrepreneur: [
    { category:'government_id', label:'Government-Issued Identity Document', required:true, desc:'Passport, national ID, or equivalent.' },
    { category:'tax_id_document', label:'National Tax / Identification Number Document', required:true, desc:'Tax identification document for KYC and tax reporting.' },
    { category:'address_confirmation', label:'Proof of Permanent Address', required:true, desc:'Utility bill, lease, or official document confirming address.' },
    { category:'business_activity', label:'Business Certificate, DBA, Professional License, or Activity Proof', required:true, desc:'Documentation of business or professional activity.' },
    { category:'community_purpose', label:'Community Purpose Statement', required:true, desc:'How your participation serves the community.' },
    { category:'ethics_declaration', label:'Professional Ethics Declaration', required:true, desc:'Commitment to professional ethics.' },
    { category:'business_registration', label:'Business Registration', required:false, desc:'Business license or registration if applicable.' },
    { category:'tax_registration', label:'Tax Registration', required:false, desc:'Additional tax registration documentation.' },
    { category:'professional_license', label:'Professional License', required:false, desc:'Required if you operate in a licensed profession.' },
    { category:'website_proof', label:'Website / Social Proof', required:false, desc:'URL or screenshot of online presence.' },
    { category:'portfolio', label:'Portfolio / Business Profile', required:false, desc:'Portfolio, brochure, or business profile document.' },
  ],
  merchant_professional: [
    { category:'business_registration', label:'Business Registration or Professional License', required:true, desc:'Official business license or professional registration.' },
    { category:'tax_id_document', label:'Business Tax ID / National Business Identification Number', required:true, desc:'Tax identification for KYB and processor compliance.' },
    { category:'representative_id', label:'Authorized Representative Identity Document', required:true, desc:'Government-issued ID of business owner or representative.' },
    { category:'address_confirmation', label:'Proof of Business Address', required:true, desc:'Utility bill, lease, or official document confirming business address.' },
    { category:'services_description', label:'Description of Products / Services', required:true, desc:'Written description of products or services offered.' },
    { category:'community_participation', label:'Community Participation Statement', required:true, desc:'How the business serves or benefits the community.' },
    { category:'ethics_declaration', label:'Professional Ethics Declaration', required:true, desc:'Commitment to professional ethics standards.' },
    { category:'insurance_certificate', label:'Insurance Certificate', required:false, desc:'Liability or professional insurance documentation.' },
    { category:'chamber_membership', label:'Chamber Membership Proof', required:false, desc:'Proof of chamber of commerce membership.' },
    { category:'website_proof', label:'Storefront / Website / Social Proof', required:false, desc:'Online or physical presence documentation.' },
    { category:'benefit_proposal', label:'Discount / Benefit Participation Proposal', required:false, desc:'Proposed discounts or benefits for ecosystem members.' },
  ],
  chamber_association: [
    { category:'legal_registration', label:'Legal Registration / Charter', required:true, desc:'Official registration or charter document.' },
    { category:'bylaws', label:'Bylaws / Governing Documents', required:true, desc:'Organizational constitution or governing framework.' },
    { category:'tax_id_document', label:'Tax ID / National Entity Identification Number', required:true, desc:'Tax identification document for KYB compliance.' },
    { category:'officer_resolution', label:'Officer Resolution / Authorized Representative Declaration', required:true, desc:'Document naming leadership or authorized representative.' },
    { category:'address_confirmation', label:'Proof of Permanent Address', required:true, desc:'Utility bill, lease, or official document confirming address.' },
    { category:'member_description', label:'Description of Member Businesses / Associations Served', required:true, desc:'Overview of businesses and associations served.' },
    { category:'community_development', label:'Community & Economic Development Statement', required:true, desc:'Statement of community and economic development purpose.' },
    { category:'ethics_declaration', label:'Professional Ethics Declaration', required:true, desc:'Commitment to professional ethics standards.' },
    { category:'membership_directory', label:'Membership Directory Summary', required:false, desc:'Summary of member businesses.' },
    { category:'leadership_list', label:'Chamber Leadership List', required:false, desc:'Names and titles of chamber leadership.' },
    { category:'partnership_proposal', label:'Partnership Proposal', required:false, desc:'Proposed partnership or activation plan.' },
    { category:'event_history', label:'Event / Business Activation History', required:false, desc:'Documentation of past events or business programs.' },
  ],
  strategic_partner_sponsor: [
    { category:'legal_registration', label:'Legal Entity Registration', required:true, desc:'Official business or entity registration document.' },
    { category:'tax_id_document', label:'Tax ID / National Entity Identification Number', required:true, desc:'Tax identification document for KYB and processor compliance.' },
    { category:'representative_id', label:'Authorized Representative Identity Document', required:true, desc:'Government-issued ID of authorized representative.' },
    { category:'address_confirmation', label:'Proof of Permanent Address', required:true, desc:'Utility bill, lease, or official document confirming address.' },
    { category:'partnership_interest', label:'Sponsorship / Partnership Interest Statement', required:true, desc:'Written statement of sponsorship or partnership interest.' },
    { category:'community_benefit', label:'Community Benefit Statement', required:true, desc:'How the partnership benefits the community.' },
    { category:'ethics_declaration', label:'Professional Ethics Declaration', required:true, desc:'Commitment to professional ethics standards.' },
    { category:'sponsorship_proposal', label:'Sponsorship Proposal', required:false, desc:'Detailed sponsorship or partnership proposal.' },
    { category:'corporate_profile', label:'Corporate Profile', required:false, desc:'Company overview or corporate profile document.' },
    { category:'csr_documentation', label:'CSR / Community Impact Documentation', required:false, desc:'Corporate social responsibility or impact reports.' },
    { category:'marketing_contact', label:'Marketing Contact Information', required:false, desc:'Marketing department or partnership contact details.' },
  ],
};
