'use client';
export function G({label,children}){return <fieldset className="space-y-2.5"><legend className="text-[9px] font-bold tracking-widest uppercase text-gold mb-1">{label}</legend>{children}</fieldset>}
export function R2({children}){return <div className="grid grid-cols-2 gap-2.5">{children}</div>}
const cls='w-full bg-navy-950 border border-surface-border rounded-lg px-3 py-2 text-sm text-surface-primary placeholder:text-surface-muted outline-none transition-all focus:border-gold focus:ring-1 focus:ring-gold-dim';
export function F({n,l,t='text',req}){return <div><label className="block text-[10px] font-medium text-surface-secondary mb-0.5">{l}{req&&<span className="text-gold ml-0.5">*</span>}</label><input name={n} type={t} required={req} className={cls}/></div>}
export function TA({n,l,req,rows=2}){return <div><label className="block text-[10px] font-medium text-surface-secondary mb-0.5">{l}{req&&<span className="text-gold ml-0.5">*</span>}</label><textarea name={n} rows={rows} required={req} className={cls+' resize-y'}/></div>}
export function Sel({n,l,opts}){return <div><label className="block text-[10px] font-medium text-surface-secondary mb-0.5">{l}</label><select name={n} className={cls+' appearance-none'}><option value="">Select...</option>{opts.map(o=><option key={o} value={o}>{o}</option>)}</select></div>}
export function C({n,l,req}){return <label className="flex items-start gap-2 cursor-pointer group"><input type="checkbox" name={n} required={req} className="mt-0.5 w-3 h-3 rounded border-surface-border bg-navy-950 text-gold accent-gold flex-shrink-0"/><span className="text-[10px] text-surface-secondary leading-relaxed group-hover:text-surface-primary transition-colors">{l}</span></label>}
export function Declarations(){return <><G label="Declarations"><C n="decl_wellbeing" l="The applicant declares that the entity exists to further the well-being of its community and is committed to upholding the highest standards of professional ethics in its field, service area, and community responsibilities." req/><C n="decl_ethics" l="The applicant commits to operating in accordance with the participation standards, compliance requirements, and ecosystem guidelines of Economic Empowerment." req/></G><G label="Acknowledgments"><C n="ack1" l="I understand that submission does not guarantee approval." req/><C n="ack2" l="I understand that no income is guaranteed." req/></G></>}
